serverUrl: http://localhost:8086
username: user
password: password
databaseName: hcmus
measures:
  - name: metrics
    tags :
      - host
    schema:
      host: string
      process: string
      owner: string
      cpu: double
      memory: double
    data:
      - host: host
        process: process1
        owner: userA
        cpu: 2.0
        memory: 2.0
  - name: heartbeats
    tags :
      - host
    schema:
      host: string
      cpu: double
      memory: double
    data:
      - host: host
        cpu: 2.0
        memory: 2.0
measureAction: drop #drop/delete/none
continuousQueries: []
